-- Add down migration script here
-- aplicaciones-para-ubuntu
DELETE FROM VIDEOS WHERE youtube_id='NkcF6n_7CmI';
DELETE FROM VIDEOS WHERE youtube_id='OZSBnykLuoI';
DELETE FROM VIDEOS WHERE youtube_id='kegJbEwLNHg';
DELETE FROM VIDEOS WHERE youtube_id='RsazE3Gaw3c';
DELETE FROM VIDEOS WHERE youtube_id='ocd-ksWIDos';
DELETE FROM VIDEOS WHERE youtube_id='cpqgPwWP0mE';
DELETE FROM VIDEOS WHERE youtube_id='lMTzjrgZ13M';
DELETE FROM VIDEOS WHERE youtube_id='jD0oWw1RhAg';
DELETE FROM VIDEOS WHERE youtube_id='lH6M3At80m8';
DELETE FROM VIDEOS WHERE youtube_id='wJV1i0MNg5Q';
DELETE FROM VIDEOS WHERE youtube_id='uWGZ_BIYGJI';
DELETE FROM VIDEOS WHERE youtube_id='Z_BOqYvH4Jw';
DELETE FROM VIDEOS WHERE youtube_id='Bxa2aogZ7t0';
DELETE FROM VIDEOS WHERE youtube_id='TX1Vqn5eAd8';
DELETE FROM VIDEOS WHERE youtube_id='CoQ7O7gO_sk';
DELETE FROM VIDEOS WHERE youtube_id='fJxk33xcNWo';
DELETE FROM VIDEOS WHERE youtube_id='kYsyVOD9sUo';
DELETE FROM VIDEOS WHERE youtube_id='XT57Th5TxNA';
DELETE FROM VIDEOS WHERE youtube_id='0jfOPv7BSN8';
DELETE FROM VIDEOS WHERE youtube_id='ApXJ0E7B4us';
DELETE FROM VIDEOS WHERE youtube_id='LSdflcz4X2w';
DELETE FROM VIDEOS WHERE youtube_id='divxMhJtzok';
-- bot-para-telegram
DELETE FROM VIDEOS WHERE youtube_id='_o8-gD2P7xA';
DELETE FROM VIDEOS WHERE youtube_id='z_XItEbXuf0';
DELETE FROM VIDEOS WHERE youtube_id='hjHjshC9l0Y';
DELETE FROM VIDEOS WHERE youtube_id='Fw71_U6Bx6c';
DELETE FROM VIDEOS WHERE youtube_id='lFXqoblxM7w';
DELETE FROM VIDEOS WHERE youtube_id='oszhHQ7L0RQ';
DELETE FROM VIDEOS WHERE youtube_id='YHZZc3J4i4E';
DELETE FROM VIDEOS WHERE youtube_id='JIuDYfYY_T8';
DELETE FROM VIDEOS WHERE youtube_id='Of2rN4CuqAA';
DELETE FROM VIDEOS WHERE youtube_id='ILnLzB03Fvc';
DELETE FROM VIDEOS WHERE youtube_id='i4jWYRPY23w';
DELETE FROM VIDEOS WHERE youtube_id='zDngVHTOVDc';
DELETE FROM VIDEOS WHERE youtube_id='78eIqzkNL9I';
